# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\params.ui',
# licensing of '.\params.ui' applies.
#
# Created: Fri Aug 16 11:24:13 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ParamsForm(object):
    def setupUi(self, ParamsForm):
        ParamsForm.setObjectName("ParamsForm")
        ParamsForm.resize(286, 491)
        self.gridLayout = QtWidgets.QGridLayout(ParamsForm)
        self.gridLayout.setObjectName("gridLayout")
        self.lbDataRate = QtWidgets.QLabel(ParamsForm)
        self.lbDataRate.setObjectName("lbDataRate")
        self.gridLayout.addWidget(self.lbDataRate, 1, 0, 1, 1)
        self.cbVar7 = QtWidgets.QComboBox(ParamsForm)
        self.cbVar7.setObjectName("cbVar7")
        self.gridLayout.addWidget(self.cbVar7, 9, 1, 1, 1)
        self.lbVar10 = QtWidgets.QLabel(ParamsForm)
        self.lbVar10.setObjectName("lbVar10")
        self.gridLayout.addWidget(self.lbVar10, 12, 0, 1, 1)
        self.lbNumVar = QtWidgets.QLabel(ParamsForm)
        self.lbNumVar.setMinimumSize(QtCore.QSize(120, 0))
        self.lbNumVar.setObjectName("lbNumVar")
        self.gridLayout.addWidget(self.lbNumVar, 0, 0, 1, 1)
        self.spinNumVar = QtWidgets.QSpinBox(ParamsForm)
        self.spinNumVar.setMinimum(1)
        self.spinNumVar.setMaximum(10)
        self.spinNumVar.setObjectName("spinNumVar")
        self.gridLayout.addWidget(self.spinNumVar, 0, 1, 1, 1)
        self.cbVar4 = QtWidgets.QComboBox(ParamsForm)
        self.cbVar4.setObjectName("cbVar4")
        self.gridLayout.addWidget(self.cbVar4, 6, 1, 1, 1)
        self.cbVar3 = QtWidgets.QComboBox(ParamsForm)
        self.cbVar3.setObjectName("cbVar3")
        self.gridLayout.addWidget(self.cbVar3, 5, 1, 1, 1)
        self.cbVar2 = QtWidgets.QComboBox(ParamsForm)
        self.cbVar2.setObjectName("cbVar2")
        self.gridLayout.addWidget(self.cbVar2, 4, 1, 1, 1)
        self.cbVar1 = QtWidgets.QComboBox(ParamsForm)
        self.cbVar1.setObjectName("cbVar1")
        self.gridLayout.addWidget(self.cbVar1, 3, 1, 1, 1)
        self.lbVar2 = QtWidgets.QLabel(ParamsForm)
        self.lbVar2.setObjectName("lbVar2")
        self.gridLayout.addWidget(self.lbVar2, 4, 0, 1, 1)
        self.cbVar9 = QtWidgets.QComboBox(ParamsForm)
        self.cbVar9.setObjectName("cbVar9")
        self.gridLayout.addWidget(self.cbVar9, 11, 1, 1, 1)
        self.lbVar3 = QtWidgets.QLabel(ParamsForm)
        self.lbVar3.setObjectName("lbVar3")
        self.gridLayout.addWidget(self.lbVar3, 5, 0, 1, 1)
        self.lbVar9 = QtWidgets.QLabel(ParamsForm)
        self.lbVar9.setObjectName("lbVar9")
        self.gridLayout.addWidget(self.lbVar9, 11, 0, 1, 1)
        self.cbVar5 = QtWidgets.QComboBox(ParamsForm)
        self.cbVar5.setObjectName("cbVar5")
        self.gridLayout.addWidget(self.cbVar5, 7, 1, 1, 1)
        self.lbVar7 = QtWidgets.QLabel(ParamsForm)
        self.lbVar7.setObjectName("lbVar7")
        self.gridLayout.addWidget(self.lbVar7, 9, 0, 1, 1)
        self.btnCancel = QtWidgets.QPushButton(ParamsForm)
        self.btnCancel.setObjectName("btnCancel")
        self.gridLayout.addWidget(self.btnCancel, 13, 1, 1, 1)
        self.lbVar8 = QtWidgets.QLabel(ParamsForm)
        self.lbVar8.setObjectName("lbVar8")
        self.gridLayout.addWidget(self.lbVar8, 10, 0, 1, 1)
        self.dialDataRate = QtWidgets.QDial(ParamsForm)
        self.dialDataRate.setMaximum(5)
        self.dialDataRate.setPageStep(1)
        self.dialDataRate.setNotchesVisible(True)
        self.dialDataRate.setObjectName("dialDataRate")
        self.gridLayout.addWidget(self.dialDataRate, 1, 1, 1, 1)
        self.cbVar8 = QtWidgets.QComboBox(ParamsForm)
        self.cbVar8.setObjectName("cbVar8")
        self.gridLayout.addWidget(self.cbVar8, 10, 1, 1, 1)
        self.lbVar4 = QtWidgets.QLabel(ParamsForm)
        self.lbVar4.setObjectName("lbVar4")
        self.gridLayout.addWidget(self.lbVar4, 6, 0, 1, 1)
        self.lbVar5 = QtWidgets.QLabel(ParamsForm)
        self.lbVar5.setObjectName("lbVar5")
        self.gridLayout.addWidget(self.lbVar5, 7, 0, 1, 1)
        self.lbVar1 = QtWidgets.QLabel(ParamsForm)
        self.lbVar1.setObjectName("lbVar1")
        self.gridLayout.addWidget(self.lbVar1, 3, 0, 1, 1)
        self.lbVar6 = QtWidgets.QLabel(ParamsForm)
        self.lbVar6.setObjectName("lbVar6")
        self.gridLayout.addWidget(self.lbVar6, 8, 0, 1, 1)
        self.cbVar10 = QtWidgets.QComboBox(ParamsForm)
        self.cbVar10.setObjectName("cbVar10")
        self.gridLayout.addWidget(self.cbVar10, 12, 1, 1, 1)
        self.cbVar6 = QtWidgets.QComboBox(ParamsForm)
        self.cbVar6.setObjectName("cbVar6")
        self.gridLayout.addWidget(self.cbVar6, 8, 1, 1, 1)
        self.btnOk = QtWidgets.QPushButton(ParamsForm)
        self.btnOk.setObjectName("btnOk")
        self.gridLayout.addWidget(self.btnOk, 13, 0, 1, 1)

        self.retranslateUi(ParamsForm)
        QtCore.QMetaObject.connectSlotsByName(ParamsForm)

    def retranslateUi(self, ParamsForm):
        ParamsForm.setWindowTitle(QtWidgets.QApplication.translate("ParamsForm", "Set Parameters", None, -1))
        self.lbDataRate.setText(QtWidgets.QApplication.translate("ParamsForm", "Data Rate: 50Hz", None, -1))
        self.lbVar10.setText(QtWidgets.QApplication.translate("ParamsForm", "Param10", None, -1))
        self.lbNumVar.setText(QtWidgets.QApplication.translate("ParamsForm", "Number of Variables", None, -1))
        self.lbVar2.setText(QtWidgets.QApplication.translate("ParamsForm", "Param2", None, -1))
        self.lbVar3.setText(QtWidgets.QApplication.translate("ParamsForm", "Param3", None, -1))
        self.lbVar9.setText(QtWidgets.QApplication.translate("ParamsForm", "Param9", None, -1))
        self.lbVar7.setText(QtWidgets.QApplication.translate("ParamsForm", "Param7", None, -1))
        self.btnCancel.setText(QtWidgets.QApplication.translate("ParamsForm", "Cancel", None, -1))
        self.lbVar8.setText(QtWidgets.QApplication.translate("ParamsForm", "Param8", None, -1))
        self.lbVar4.setText(QtWidgets.QApplication.translate("ParamsForm", "Param4", None, -1))
        self.lbVar5.setText(QtWidgets.QApplication.translate("ParamsForm", "Param5", None, -1))
        self.lbVar1.setText(QtWidgets.QApplication.translate("ParamsForm", "Param1", None, -1))
        self.lbVar6.setText(QtWidgets.QApplication.translate("ParamsForm", "Param6", None, -1))
        self.btnOk.setText(QtWidgets.QApplication.translate("ParamsForm", "Ok", None, -1))

